# Default values for kyverno installation
replicaCount: 1

image:
  repository: ghcr.io/kyverno/kyverno
  tag: v1.10.0
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
